name: Build Mod

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7

      - name: Build with Gradle
        run: gradle build

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: AutoRodSwitch
          path: build/libs/*.jar

